development:
  adapter: postgresql
  encoding: unicode
  database: jchef_dev
  pool: 5
  username: jerny
  password:
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: jchef_test
  pool: 5
  username: jerny
  password:
staging:
  adapter: postgresql
  encoding: unicode
  database: jchef_dev
  pool: 5
  username: jerny
  password:
  host: localhost
#production:
  #adapter: postgresql
  #encoding: unicode
  #database: chef-test_production
  #pool: 5
  #username: chef-test
  #password:
