development:
  adapter: postgresql
  encoding: unicode
  database: hive_apps
  pool: 5
  username: root
  password: root
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: jchef_test
  pool: 5
  username: jerny
  password:

#production:
  #adapter: postgresql
  #encoding: unicode
  #database: chef-test_production
  #pool: 5
  #username: chef-test
  #password:
